import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components/shared";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CookBooked",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + ' bg-background min-h-screen flex flex-col'}>
        <Navbar />
        <div className="flex-grow">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
