import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/shared";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CookBooked",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + ' bg-background'}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
